books/urls.py
from django.conf.urls import patterns, url
from books import views

urlpatterns = patterns(
    '',
    url(r'^$', views.BookList.as_view(), name='book_list'),
    url(r'^(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^add/$', views.AuthorCreateView.as_view(), name='add_author_and_books'),
    url(r'^(?P<pk>\d+)/edit/$', views.AuthorUpdateView.as_view(), name='edit_author_and_books'),
    url(r'^authors/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^authors/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
)

config/urls.py
from django.conf.urls import patterns, include
from django.contrib import admin
from django.conf import settings

handler500 = 'utils.views.server_error'

urlpatterns = patterns('')

# Debug/Development URLs
if settings.DEBUG is True:  # pragma: no cover
    urlpatterns += patterns(
        '',
        (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    )

# Admin Site
admin.autodiscover()

# Includes
urlpatterns += patterns(
    '',
    (r'^admin/', include(admin.site.urls)),
    (r'^grappelli/', include('grappelli.urls')),
    (r'', include('books.urls')),
)

books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('author_detail', [self.pk])


class Book(models.Model):
    author = models.ForeignKey(Author)
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('book_detail', [self.pk])

books/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Author, Book


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('name', )


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('author', 'title')

BookFormSet = inlineformset_factory(Author, Book, extra=0, min_num=1, fields=('title', ))

books/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.shortcuts import redirect
from .models import Book, Author
from .forms import AuthorForm, BookFormSet


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class AuthorCreateView(FormsetMixin, CreateView):
    template_name = 'books/author_and_books_form.html'
    model = Author
    form_class = AuthorForm
    formset_class = BookFormSet


class AuthorUpdateView(FormsetMixin, UpdateView):
    template_name = 'books/author_and_books_form.html'
    is_update_view = True
    model = Author
    form_class = AuthorForm
    formset_class = BookFormSet


class BookList(ListView):

    model = Book


class BookDetail(DetailView):

    model = Book


class AuthorList(ListView):

    model = Author


class AuthorDetail(DetailView):

    model = Author

utils/views.py
from django.conf import settings
from django.template import Context, loader


def server_error(request, template_name='500.html'):

    "Always includes STATIC_URL"
    from django.http import HttpResponseServerError

    # Use the 500 template for each program if it exists
    url_segment = request.path_info.strip("/").split("/")
    program_500_template = "%s/500.html" % url_segment[0]
    t = loader.select_template([program_500_template, '500.html'])

    return HttpResponseServerError(t.render(Context({'STATIC_URL': settings.MEDIA_URL})))

books/templates/books/author_and_books_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}{% if form.instance.pk %}Edit{% else %}Add{% endif %} Author and Books{% endblock title %}

{% block link %}{{ block.super }}
    <style type="text/css">
    .errorlist {
        list-style: none;
        color: #B94A48;
        margin: 0px 0px 9px 0px;
        padding: 0px;
    }
    </style>
{% endblock link %}

{% block bottom_script %}{{ block.super }}
    <script type="text/html" id="book-template">
    <div id="book-__prefix__">
        {{ formset.empty_form|bootstrap }}
    </div>
    </script>
    <script>
    $(function() {
        $('.add-book').click(function(ev){
            ev.preventDefault();
            var count = parseInt($('#id_book_set-TOTAL_FORMS').attr('value'), 10);
            var tmplMarkup = $('#book-template').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
            console.log(compiledTmpl);
            $('div.books').append(compiledTmpl);
            $('#id_book_set-TOTAL_FORMS').attr('value', count + 1);
        });
    });
    </script>
{% endblock bottom_script %}


{% block base_content %}

<div class="page-header">
  <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Author and Books</h1>
</div>

<form action="." method="post">
    {{ formset.management_form }}
    {% csrf_token %}

    <legend>Author</legend>
    <div class="author">
    {{ form|bootstrap }}
    </div>

    <legend>
        <div class="pull-right"><a href="#" class="btn btn-inverse add-book"><i class="icon-plus icon-white"></i> Add Book</a></div>
        Books
    </legend>
    <div class="books form-inline">
        {% for form in formset %}
            {{ form|bootstrap }}
        {% endfor %}
    </div>
  <div class="form-actions">
     <button type="submit" class="btn btn-primary">Save</button>
   </div>
 </form>

{% endblock base_content %}

books/templates/books/author_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock title %}

{% block base_content %}

<ul class="breadcrumb">
  <li><a href="{% url 'author_list' %}">Authors</a> <span class="divider">/</span></li>
  <li class="active">{{ object.name }}</li>
</ul>

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'edit_author_and_books' object.pk %}"><i class="icon-edit icon-white"></i> Edit Author and Books</a>
    <h1>{{ object.name }}</h1>
</div>

<h2>Author's Books</h2>

<ul>
    {% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
    {% endfor %}
</ul>

{% endblock base_content %}

books/templates/books/author_list.html
{% extends "base.html" %}

{% block title %}Authors{% endblock title %}

{% block base_content %}

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'add_author_and_books' %}"><i class="icon-plus icon-white"></i> Add Author and Books</a>
    <h1>Author List</h1>
</div>

<table class="table table-striped">
    <tr>
        <th>Author</th>
    </tr>
    {% for object in object_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
    </tr>
    {% endfor %}

</table>

{% endblock base_content %}

books/templates/books/book_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block base_content %}

<ul class="breadcrumb">
  <li><a href="{% url 'book_list' %}">Books</a> <span class="divider">/</span></li>
  <li class="active">{{ object.title }}</li>
</ul>

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'edit_author_and_books' object.author.pk %}"><i class="icon-edit icon-white"></i> Edit</a>
    <h1>{{ object.title }}</h1>
</div>

<p>By {{ object.author }}</p>

{% endblock base_content %}

books/templates/books/book_list.html
{% extends "base.html" %}

{% block title %}Books{% endblock title %}

{% block base_content %}

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'add_author_and_books' %}"><i class="icon-plus icon-white"></i> Add Author and Books</a>
    <h1>Book List</h1>
</div>

<table class="table table-striped">
    <tr>
        <th>Book</th>
        <th>Author</th>
    </tr>
    {% for object in object_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td>
        <td><a href="{{ object.author.get_absolute_url }}">{{ object.author }}</a></td>
    </tr>
    {% endfor %}

</table>

{% endblock base_content %}

templates/base/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        {% block head %}{% block title_tag %}<title>{% block title %}{% if page.title %}{{ page.title }}{% endif %}{% endblock %}{% if site_name %} - {{ site_name }}{% endif %}</title>{% endblock %}
        {% block meta %}<meta name="viewport" content="width=device-width, initial-scale=1.0">{% endblock meta %}

        {% block link %}<!-- Le styles -->
        <link href="{{ STATIC_URL }}css/bootstrap/bootstrap.min.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
        <link href="{{ STATIC_URL }}css/bootstrap/bootstrap-responsive.min.css" rel="stylesheet">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        {% comment %}
        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="../assets/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png"> {% endcomment %}{% endblock link %}
        {% block script %}{% endblock script %}{% include "google-analytics.html" %}{% endblock head %}
    </head>

    <body{% block body_attr %} class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}"{% endblock %}>

        {% block base_header %}
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">{{ site_name }}</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li><a href="/">Home</a></li>
                            <li><a href="{% url 'book_list' %}">Books</a></li>
                            <li><a href="{% url 'author_list' %}">Authors</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        {% endblock base_header %}

        <div class="container">
            {% block base_content %}
            {% endblock base_content %}

            {% block base_footer %}
            <hr>
            <footer>
                <p>&copy; {{ site_name }} {% now "Y" %}</p>
            </footer>
            {% endblock base_footer %}

        </div> <!-- /container -->

        {% block bottom_script %}
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}css/bootstrap/js/bootstrap.min.js"></script>{% endblock bottom_script %}

    </body>
</html>

templates/base/google-analytics.html
{% if not debug %}
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-xxxxxxx-x']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>{% endif %}